extend schema {
    subscription: Subscription
}

type KogitoMetadata {
    lastUpdate: DateTime!
    processInstances: [ProcessInstanceMeta]
}

input KogitoMetadataOrderBy {
    lastUpdate: OrderBy
}

input KogitoMetadataArgument {
    lastUpdate: DateArgument
    processInstances: ProcessInstanceMetaArgument
}

type ProcessInstanceMeta {
    id: String!
    processId: String!
    version: String
    processName: String
    parentProcessInstanceId: String
    rootProcessInstanceId: String
    rootProcessId: String
    roles: [String!]
    state: ProcessInstanceState!
    endpoint: String!
    serviceUrl: String
    start: DateTime!
    end: DateTime
    lastUpdate: DateTime!
    businessKey: String
    createdBy: String
    updatedBy: String
}

input ProcessInstanceMetaArgument {
    id: IdArgument
    processId: StringArgument
    processName: StringArgument
    parentProcessInstanceId: IdArgument
    rootProcessInstanceId: IdArgument
    rootProcessId: StringArgument
    state: ProcessInstanceStateArgument
    endpoint: StringArgument
    roles: StringArrayArgument
    start: DateArgument
    end: DateArgument
    businessKey: StringArgument
    createdBy: StringArgument
    updatedBy: StringArgument
}



type Subscription {
    ProcessInstanceAdded: ProcessInstance!
    ProcessInstanceUpdated: ProcessInstance!
    JobAdded: Job!
    JobUpdated: Job!
}
